# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
[ ](bg:blue)\
$shell\
[](fg:blue)\
\
[](fg:lavender)\
$directory\
[](fg:lavender)\
\
$fill\
\
\
$git_branch\
$git_status\
\
\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
\
$line_break$character\
"""

right_format = """
$status$cmd_duration$time\
"""


add_newline = true
command_timeout = 300
scan_timeout = 20
continuation_prompt = "[ : ](fg:#444444)"
palette = "catppuccin_mocha"

[fill]
symbol = " "

[character]
format = "$symbol "
success_symbol = "[❯](bold blue)[❯](bold lavender)"
error_symbol = "[❯](bold peach)[❯](bold red)"
vimcmd_symbol = "[:](bold blue)[❯](bold lavender)"
vimcmd_replace_one_symbol = "[r](bold blue)[❯](bold lavender)"
vimcmd_replace_symbol = "[R](bold blue)[❯](bold lavender)"
vimcmd_visual_symbol = "[V](bold blue)[❯](bold lavender)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = "[$user ]($style)"
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[shell]
unknown_indicator = "?"
nu_indicator = ">"
bash_indicator = ""
fish_indicator = "󰈺"
zsh_indicator = "%"
ion_indicator = ""
elvish_indicator = ""
powershell_indicator = ""
cmd_indicator = ""
xonsh_indicator = "󰽯"
tcsh_indicator = "󰇴"
format = "[$indicator ]($style)"
style = "bg:blue fg:surface1"
disabled = false

[directory]
style = "bg:lavender fg:mantle"
format = "[ $path ]($style)"
truncation_length = 6
truncation_symbol = "…/"
truncate_to_repo = false

# [directory.substitutions]
# "~/workspace" = "󰵮 "
# "~/Documents" = "󰈙 "
# "~/Downloads" = " "
# "~/Music" = " "
# "~/Pictures" = " "

[git_branch]
symbol = ""
style = "bg:red fg:mantle"
format = "[](fg:red)[ $symbol $branch]($style)"

[git_status]
style = "bg:red fg:mantle"
format = "[ $all_status$ahead_behind]($style)[](fg:red)"

[time]
format = "[at $time](fg:lavender)"
disabled = false

[cmd_duration]
min_time = 2_000
show_milliseconds = true
format = "[took $duration](fg:peach) "

[status]
disabled = false
symbol = "󱗗 "
style = "fg:red"

# Languges
[docker_context]
symbol = " "
style = "bg:sky fg:mantle"
format = "[](fg:sky)[ $symbol $context ]($style)"

[c]
symbol = " "
style = "bg:sky fg:mantle"
format = "[](fg:sky)[ $symbol ($version) ]($style)"

[golang]
symbol = " "
style = "bg:sky fg:mantle"
format = "[](fg:sky)[ $symbol ($version) ]($style)"

[gradle]
style = "bg:sky fg:mantle"
format = "[](fg:sky)[ $symbol ($version) ]($style)"

[java]
symbol = " "
style = "bg:sky fg:mantle"
format = "[](fg:sky)[ $symbol ($version) ]($style)"

[nodejs]
symbol = ""
style = "bg:sky fg:mantle"
format = "[](fg:sky)[ $symbol ($version) ]($style)"

[rust]
symbol = ""
style = "bg:sky fg:mantle"
format = "[](fg:sky)[ $symbol ($version) ]($style)"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "◨ "
style = "dimmed yellow italic bold"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold bright-yellow"

[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"

#[custom.directory]
##Add: ${custom.directory}\
#style = "bg:#303030 fg:#CCCCCC"
#format = "[ $output ]($style)"
#when = true
#shell = [ 'pwd' ]

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"