# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:#9A348E)\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
[](fg:#FCA17D bg:#33658A)\
[ ](fg:#33658A)\
$line_break$character
"""

right_format = """
[\n](fg:#9A348E)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
$cmd_duration\
[](fg:#FCA17D bg:#9A348E)\
$git_branch\
$git_status\
[ ](bg:#FCA17D)
"""

# Disable the blank line at the start of the prompt
add_newline = true

command_timeout = 300
scan_timeout = 20
continuation_prompt = '[ : ](fg:#444444)'

[fill]
symbol = ' '

[character]
format = " $symbol "
#success_symbol = "[>](bold italic bright-yellow)"
#error_symbol = "[○](italic purple)"
#vimcmd_symbol = "[■](italic dimmed green)"
# not supported in zsh
# vimcmd_replace_one_symbol = "◌"
# vimcmd_replace_symbol = "□"
# vimcmd_visual_symbol = "▼"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 6
truncation_symbol = "…/"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Documents" = "󰈙 "
"~/Downloads" = " "
"~/Music" = " "
"~/Pictures" = " "
"~/workspace" = "w "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = true

[cmd_duration]
format = "[◄ $duration ](italic white)"

# Languges
[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "◨ "
style = "dimmed yellow italic bold"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold bright-yellow"

[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"