name: Build and Publish Docker Image

on:
  schedule:
    # Runs at 1:00 AM UTC every Monday
    - cron: "0 1 * * 1"
  workflow_dispatch:
    # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: ghcr.io/kboshold/codespace:latest
          timeout-minutes: 30
