name: Update README.md

on:
  push:
    branches:
      - main

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: python ./scripts/github/extract_keybindings.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated README.md